name: flutter_change_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^2.1.0
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  rive: ^0.9.1
  shared_preferences: ^2.0.15
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/rive/login_screen_character.riv
    - assets/rive/Login_Screen_Character.riv
    - assets/rive/login_screen_character.riv
    - assets/rive/Kitty.riv
    - assets/rive/Bear.riv
